#include <iostream>
#include "../include/zenith_runtime.h"

// Forward declaration of the entry point generated by Zenith transpilation
zenith::UIElement ChatScreen();

int main() {
    std::cout << "=== RUNNING COMPILED ZENITH APP ===\n";
    
    // Invoke the entry point UI component
    zenith::UIElement root = ChatScreen();
    
    std::cout << "\nRendered UI Layout Tree:\n";
    root.render();
    
    return 0;
}
